language: python
python:
- '3.6'
services: docker
git:
  depth: false
install: make docker-login build-docker
stages:
- name: publish-docker
jobs:
  include:
  - stage: publish
    name: Publish docker image
    script:
    - make docker-login publish-docker
env:
  global:
  - secure: KSFyestgFASWUXxjiT5Tqfh+IEYbEvug27bdDyUfgs29DXHHPv97CeIWk0VuyKjPneWPdsJIDSRUvFaWHJ0XLbNIFeadsv6zxQmgTQjLEhWaiDvoSeMa3YjvtwKavtDTtU3sd21jTTJAgM0+n9qg76nprY1iaqtg+JfIdXZ48ERupM4uCZCKcNE7GQsS8gabNe8S94KNOacMBG+c7O4vPr2EsQAz+xpokWWE/BMJYzlHdKOjGKd0lIHZKUdg8XVtuEfaq16sekWvVTLtheDZKtr0npBFFpkJl63QmdOicuDuJPI+Z3EeNWNNuDWBKtQ2q88HgUyZQmkkex7kYBiXX/eOz3AFo7Rfc4bkwG4Sk9XmV9OLCB3xHQkj7fegSQGcahK2S6/hmdJBVxOxD0mIbXAf9xdJ80CUEdusC1gYPxk35XHhiYNP2aXOhjmFn2T2esMWX3DS4+RKA4R5S7aKScOtPWSvqvz2lDDTfJ36dTYXi7vo7KMq2xE/fZveKMTG2CQDrBiINbhTpyAabOxt8Zl2DPHdkENmnc8k78YRsHtRTHiY5WQBZ2hbm72QTHz1yx5jgQX96tn3BPIHInM0NdwQGHvKp/cpMo6QPJHVBCEXFMjHb0i0k52WusSukP24Wye0+EMK2Pmnj7oQ6T6fk7NrMxbn3Sa1jwtVL0usKZ4=
  - secure: cmBNH/dt+7OSJ4qmYxukuznOv1S5zs3uQvGHY5wpR3rEEn9I/5hBNbqkVMEB9DbSV+VQq47YLgvKVf18rGc55esmAuWKZ3HfAXvi5tcI0KNOgxG0gda6WbW//i0rVw17Mw6v35/UUqVxtMcXV+BtHGChPYbUtWOcYHJI0nZamXhqDreqBwutu6KjIonzZx4AY2W8eR/rouKT+wYs7bw3vRwUgfdzgk/pIv+yXCVogXtWLOLb14CsJzxap7U7PSQxKSkbKQFq3XR13l3bdybfBbHEdsuktgZdPtnfHfcDj98mQhBrvZ/W6j+g89ZVYrXxJb0jKTrcrBk8UutFOh9nPoTWdYZmJa2DziVOHsY12i2WjenmTmyG7RnssMgqLel2rJARVhesqLBX9/3SIAJhA91ox4gKM2M62og4yIO/I4aCE09puCXlahAV9u+In+6AbNDSMO/M+PychOVYOuna/GIjkThxILe3jYXJrnjB/n9oW4eS9NZLWySKVgxjbOj0j3bctKXc918AuD1vhCMVlULJQBGQb+xvjcwNUsQ5KJtEQXYtGunXqyclfXswBt4bSkjv8ajicg8rrSEr5g7eSIC/9AYyvPNPiToGCBj1JYj0p+eAc8OigN2LtnkKjPyXEpJeBjimpJ9PDUpL+WUmpfAm8/vzrBavPkej1VT8PhY=
